import { Link } from "react-router-dom";
import { FiInstagram, FiMail, FiMapPin } from "react-icons/fi";
import logo from "../assets/logo.png";

const links = [
  { label: "Home", to: "/" },
  { label: "About", to: "/about" },
  { label: "Workshops", to: "/workshops" },
  { label: "Gallery", to: "/gallery" },
  { label: "Contact", to: "/contact" },
];

export default function Footer() {
  return (
    <footer className="bg-neutral-900 text-neutral-300 pt-16 pb-8">
      <div className="max-w-7xl mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12 pb-12 border-b border-neutral-800">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-2 mb-4">
              <img
                src={logo}
                alt="Creative Detox logo"
                className="h-12 w-12 rounded-full bg-white/95 p-1 object-contain"
              />
              <div className="leading-none">
                <span className="font-display font-bold text-white text-lg">Creative</span>
                <span className="font-display font-bold text-sage-light text-lg ml-1">Detox</span>
              </div>
            </div>
            <p className="font-body text-sm text-neutral-400 leading-relaxed max-w-xs">
              Art for your mental escape. We create safe, joyful spaces where creativity 
              meets wellness — no experience required.
            </p>
            <div className="flex items-center gap-4 mt-6">
              <a
                href="https://www.instagram.com/creative.detox.art?igsh=MWp6Nno0ZW9heWFjZg%3D%3D&utm_source=qr"
                target="_blank"
                rel="noreferrer"
                className="w-10 h-10 rounded-full bg-neutral-800 hover:bg-berry transition-colors flex items-center justify-center group"
              >
                <FiInstagram size={16} className="text-neutral-400 group-hover:text-white transition-colors" />
              </a>
              <a
                href="mailto:creativedetox@gmail.com"
                className="w-10 h-10 rounded-full bg-neutral-800 hover:bg-berry transition-colors flex items-center justify-center group"
              >
                <FiMail size={16} className="text-neutral-400 group-hover:text-white transition-colors" />
              </a>
            </div>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="font-display font-semibold text-white text-lg mb-5">Quick Links</h4>
            <ul className="flex flex-col gap-3">
              {links.map((link) => (
                <li key={link.to}>
                  <Link
                    to={link.to}
                    className="font-body text-sm text-neutral-400 hover:text-white transition-colors hover:translate-x-1 inline-block"
                  >
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Contact Info */}
          <div>
            <h4 className="font-display font-semibold text-white text-lg mb-5">Get In Touch</h4>
            <ul className="flex flex-col gap-4">
              <li className="flex items-start gap-3">
                <FiMail size={16} className="text-berry mt-0.5 flex-shrink-0" />
                <a href="mailto:creativedetox@gmail.com" className="font-body text-sm text-neutral-400 hover:text-white transition-colors">
                  creativedetox@gmail.com
                </a>
              </li>
              <li className="flex items-start gap-3">
                <FiInstagram size={16} className="text-berry mt-0.5 flex-shrink-0" />
                <a href="https://www.instagram.com/creative.detox.art?igsh=MWp6Nno0ZW9heWFjZg%3D%3D&utm_source=qr" target="_blank" rel="noreferrer" className="font-body text-sm text-neutral-400 hover:text-white transition-colors">
                  @creative.detox.art
                </a>
              </li>
              <li className="flex items-start gap-3">
                <FiMapPin size={16} className="text-berry mt-0.5 flex-shrink-0" />
                <span className="font-body text-sm text-neutral-400">Beirut, Lebanon</span>
              </li>
            </ul>
            <Link to="/workshops" className="mt-6 btn-berry text-xs px-5 py-2.5 inline-flex">
              Join a Workshop
            </Link>
          </div>
        </div>

        <div className="pt-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="font-body text-xs text-neutral-600">
            © {new Date().getFullYear()} Creative Detox. All rights reserved.
          </p>
          <p className="font-body text-xs text-neutral-600">
            Website generated by Jinan Ghannam.
          </p>
        </div>
      </div>
    </footer>
  );
}
